server:
  port: 8090
  servlet:
    context-path: /  #项目发布路径
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root

#引入SpringMVC配置
  mvc:         #引入mvn配置
    view:
      prefix: /WEB-INF/     # /默认代表根目录 src/main/webapp
      suffix: .jsp

#mybatis-plush配置
mybatis-plus:
  #定义别名包  resultType的映射可以省略包路径
  type-aliases-package: com.jt.pojo
  #加载mapper的映射文件
  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射 
  #使用说明: 1.必须按照驼峰规则的规定  去掉_线,并且之后字母"大写"
  #         2.如果开启驼峰规则,必须按照要求  属性user_id   字段user_id   
  configuration:
    map-underscore-to-camel-case: true
 

#配置数据库日志
logging:  level:    com.jt.mapper: debug







  
  